### ISSUE TITLE
Compiling Cyrus IMAP 3.10 or 3.12 with libical 4 (libicalvcard) fails

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#6031]
The [Release notes for Cyrus IMAP 3.10](https://www.cyrusimap.org/3.10/imap/download/release-notes/3.10/x/3.10.0.html) state:

> Adds experimental support for JMAP Contacts per upcoming IETF standards. Requires the not-yet-released libicalvcard

Compiling Cyrus IMAP 3.10.2 (commit 23a5b5f05c1820f) and Cyrus IMAP 3.12.2 (commit 76ee16c7ff07c13) with libical 4.0.1 (commit 50858c6f91fb275d989589) fails, because vcardstructuredtype is incomplete typedef.

-----------------------
Cyrus 3.12
```
  CC       imap/libcyrus_imap_la-index.lo
imap/index.c: In function 'extract_vcardbuf':
imap/index.c:5534:9: error: variable 'st' has initializer but incomplete type
 5534 |         vcardstructuredtype st = { 1, { 0 } };                                                          
      |         ^~~~~~~~~~~~~~~~~~~                
imap/index.c:5534:36: warning: excess elements in struct initializer   
 5534 |         vcardstructuredtype st = { 1, { 0 } };
      |                                    ^
imap/index.c:5534:36: note: (near initialization for 'st')
imap/index.c:5534:39: error: extra brace group at end of initializer
 5534 |         vcardstructuredtype st = { 1, { 0 } };
      |                                       ^                                                                 
imap/index.c:5534:39: note: (near initialization for 'st')
imap/index.c:5534:39: warning: excess elements in struct initializer
imap/index.c:5534:39: note: (near initialization for 'st')
imap/index.c:5534:29: error: storage size of 'st' isn't known
 5534 |         vcardstructuredtype st = { 1, { 0 } };
      |                             ^~
imap/index.c:5577:32: error: invalid use of incomplete typedef 'vcardstructuredtype' {aka 'struct vcardstructuredtype_impl'}
 5577 |             for (f = 0; f < stp->num_fields; f++) {
      |                                ^~
imap/index.c:5578:42: error: invalid use of incomplete typedef 'vcardstructuredtype' {aka 'struct vcardstructuredtype_impl'}
 5578 |                 vcardstrarray *vals = stp->field[f];
      |                                          ^~
imap/index.c:5534:29: warning: unused variable 'st' [-Wunused-variable]
 5534 |         vcardstructuredtype st = { 1, { 0 } };
      |                             ^~
imap/index.c: In function 'index_extract_subject':
imap/index.c:6539:11: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 6539 |         s = strchr(subj, '}') + 3;              /* literal, skip { }\r\n */
      |           ^
```
-----------------------
Cyrus 3.10
```
  CC       imap/libcyrus_imap_la-index.lo
imap/index.c: In function 'extract_vcardbuf':
imap/index.c:5527:9: error: variable 'st' has initializer but incomplete type
 5527 |         vcardstructuredtype st = { 1, { 0 } };                                                          
      |         ^~~~~~~~~~~~~~~~~~~                
imap/index.c:5527:36: warning: excess elements in struct initializer   
 5527 |         vcardstructuredtype st = { 1, { 0 } };
      |                                    ^
imap/index.c:5527:36: note: (near initialization for 'st')
imap/index.c:5527:39: error: extra brace group at end of initializer
5527 |         vcardstructuredtype st = { 1, { 0 } };
      |                                       ^                                                                 
imap/index.c:5527:39: note: (near initialization for 'st')
imap/index.c:5527:39: warning: excess elements in struct initializer
imap/index.c:5527:39: note: (near initialization for 'st')
imap/index.c:5527:29: error: storage size of 'st' isn't known
 5527 |         vcardstructuredtype st = { 1, { 0 } };
      |                             ^~
imap/index.c:5570:32: error: invalid use of incomplete typedef 'vcardstructuredtype' {aka 'struct vcardstructuredtype_impl'}
 5570 |             for (f = 0; f < stp->num_fields; f++) {
      |                                ^~
imap/index.c:5571:42: error: invalid use of incomplete typedef 'vcardstructuredtype' {aka 'struct vcardstructuredtype_impl'}
 5571 |                 vcardstrarray *vals = stp->field[f];
      |                                          ^~
make[2]: *** [Makefile:5732: imap/libcyrus_imap_la-index.lo] Error 1
 imap/index.c:5527:29: warning: unused variable 'st' [-Wunused-variable]
 5527 |         vcardstructuredtype st = { 1, { 0 } };
      |                             ^~
imap/index.c: In function 'index_extract_subject':
imap/index.c:6500:11: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 6500 |         s = strchr(subj, '}') + 3;              /* literal, skip { }\r\n */
      |           ^
```

**Comment by dilyanpalauzov** [comment]
Another problem is that in 3.10 the last parameter of `vcardproperty_vanew_jsprop(…)` and `vcardcomponent_vanew(…)` is sometimes `0` instead of `NULL`.

**Comment by elliefm** [comment]
This won't be fixed; 3.10 and 3.12 will not be updated for libical 4.  You should stick with libical 3 for these releases.  If you want the experimental vcard features, you'll need a patched version of libical 3.

The [cyruslibs](https://github.com/cyrusimap/cyruslibs) repository contains a patched version of libical (among other things).  The tag [cyruslibs-fastmail-v68](https://github.com/cyrusimap/cyruslibs/releases/tag/cyruslibs-fastmail-v68) is known to work with 3.12, and the tag [cyruslibs-fastmail-v42](https://github.com/cyrusimap/cyruslibs/releases/tag/cyruslibs-fastmail-v42) is known to work with 3.10.  These are the versions built into the docker images that are used for CI testing of these branches.  Other tagged versions may work, but ymmv.
