### ISSUE TITLE
error: use of undeclared identifier 'CLOCK_MONOTONIC'

### ISSUE THREAD

**Issue by ryandesign** [cyrusimap/cyrus-imapd#2152]
cyrus-imapd 2.4.20 builds on macOS 10.12 Sierra, but fails to build on OS X 10.11 El Capitan and earlier:

```
imapd.c:2685:23: error: use of undeclared identifier 'CLOCK_MONOTONIC'
    if (clock_gettime(CLOCK_MONOTONIC, &now) == -1) {
                      ^
imapd.c:2716:20: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        if (clock_gettime(CLOCK_MONOTONIC, &deadline) == -1) {
                          ^
```

cyrus-imapd 2.4.18 did not have this problem.

**Comment by bogdro** [comment]
This issue is nearly 6 years old, and:
- it works on newer systems, doesn't work on older (probably deprecated by now), so it may not be worthy to fix after such a long time,
- the difference between 2.4.18 and 2.4.20 it too big for me to fix with a simple patch or some `#ifdef`.

What I wanted is to point the Cyrus project at Travis CI (https://travis-ci.com/). Free for open-source projects and supports building on macOS (and Linux, FreeBSD and Windows) in the versions listed on https://docs.travis-ci.com/user/reference/osx/.

**Comment by elliefm** [comment]
We no longer do releases from the 2.4 branch, so even if someone took the time to produce a patch, and find some way to test it to prove that it works, it would still only be available to people building Cyrus from git.  Presumably those people could just upgrade instead.

**Comment by bogdro** [comment]
Hi.
Agreed. The project decides which releases to support, no problem from my side. Anyway, one less issue open, just like with #878  :)
Thank you!
