### ISSUE TITLE
Building 2.3.12 on Solaris 10 fails with "auth_krb5.c:60:18: error: krb5.h: No such file or directory"

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1006]
From: cyrus@fiddaman.net
Bugzilla-Id: 3058
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by dilyanpalauzov** [comment]
krb5.h is not part of Cyrus, but comes from MIT Kerberos and the Linux kernel:
```
$ locate krb5.h
/src/krb5-1.18.3/src/include/krb5.h
/src/krb5-1.18.3/src/include/krb5/krb5.h
/src/linux-4.14.199/include/config/rpcsec/gss/krb5.h
```
The location of krb5.h is located in configure.ac with `krb5-config --cflags`, or by calling `./configure --with-krb=`.

How the detection exactly has worked on Solaris 2.3.12 is now impossible to say, therefore I propose closing the case.
